import * as fs from 'node:fs';
import { basename, extname, join, relative, sep } from 'node:path';
import type { Shader } from './shaders.js';

/**
 * Generated sources live in the source tree so the game's own tsconfig compiles them.
 * The name is not dot-prefixed because TypeScript's wildcard includes skip dot-directories.
 */
export const generatedDir = 'generated';

export interface Found {
	/** The file's base name, which is both the export name and the type name. */
	name: string;
	path: string;
}

export function scan(dir: string, ext: string): Found[] {
	if (!fs.existsSync(dir)) return [];

	const found: Found[] = [];

	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		if (!entry.isFile() || extname(entry.name) !== ext) continue;

		found.push({ name: basename(entry.name, ext), path: join(dir, entry.name) });
	}

	return found.sort((a, b) => a.name.localeCompare(b.name));
}

/** A relative ESM specifier from `from` to `to`, with TypeScript's `.js` extension. */
export function specifier(from: string, to: string): string {
	const path = relative(from, to.replace(/\.ts$/, '.js')).split(sep).join('/');
	return path.startsWith('.') ? path : './' + path;
}

const header = '// Generated by Sumeria. Do not edit; your changes will be overwritten.\n';

interface Generated {
	dir: string;
	entities: Found[];
	renders: Found[];
	shaders: Shader[];
	/** Specifier for the compiled GLSL, which resolves the same from source and compiled trees. */
	shaderData: string;
	zones: Found[];
	/** Specifier for the world setup module, or false when the game has none. */
	world?: string | false;
	controls?: string | false;
}

export function generate(gen: Generated): void {
	fs.rmSync(gen.dir, { recursive: true, force: true });
	fs.mkdirSync(gen.dir, { recursive: true });

	const sources = Object.fromEntries(gen.shaders.map(s => [s.name, { vertex: s.vertex, fragment: s.fragment }]));

	const files: Record<string, string[]> = {
		'shaders.json': [JSON.stringify(sources, null, '\t'), ''],

		'entities.ts': [
			header,
			"import { register } from '@sumeria/core';",
			...gen.entities.map(e => `import { ${e.name} } from '${specifier(gen.dir, e.path)}';`),
			'',
			`register(${gen.entities.map(e => e.name).join(', ')});`,
			'',
		],

		'renders.ts': [
			header,
			"import { renderers, shaders, worldRenderers, zoneRenderers } from '@sumeria/render';",
			`import sources from '${gen.shaderData}' with { type: 'json' };`,
			...gen.renders.map(r => `import { ${r.name} } from '${specifier(gen.dir, r.path)}';`),
			...gen.zones.map(z => `import { ${z.name} } from '${specifier(gen.dir, z.path)}';`),
			...(gen.world ? [`import world from '${gen.world}';`] : []),
			'',
			...gen.renders.map(r => `renderers.set(${JSON.stringify(r.name)}, ${r.name});`),
			...gen.zones.map(z => `zoneRenderers.set(${JSON.stringify(z.name)}, ${z.name});`),
			...(gen.world ? ['worldRenderers.add(world);'] : []),
			'',
			'for (const [name, source] of Object.entries(sources)) shaders.set(name, source);',
			'',
		],

		'client.ts': [
			header,
			"import { input } from '@sumeria/client';",
			"import '@sumeria/client/main';",
			`import controls from '${gen.controls}' with { type: 'json' };`,
			'',
			'input.bind(controls);',
			'',
		],

		'render.ts': [header, "import './renders.js';", "import '@sumeria/render/main';", ''],

		'server.ts': [header, "import './entities.js';", "import '@sumeria/app/server_thread';", ''],
	};

	for (const [name, lines] of Object.entries(files)) {
		fs.writeFileSync(join(gen.dir, name), lines.join('\n'));
	}
}
