#!/usr/bin/env node
import type { Controls } from '@sumeria/core';
import { Controls as ControlsSchema } from '@sumeria/core';
import * as esbuild from 'esbuild';
import * as io from 'ioium/node';
import { spawn } from 'node:child_process';
import * as fs from 'node:fs';
import { createRequire } from 'node:module';
import { basename, dirname, extname, join, posix, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import * as z from 'zod';

export const BuildOptions = z.object({
	/** Reverse-DNS id for the packaged app, derived from the package name when omitted. */
	appId: z.string().optional(),
	/** Path to the app icon, relative to the package. */
	icon: z.string().optional(),
	/** Path to the controls config, relative to the package. */
	controls: z.string().default('controls.json'),
	/** Where the game's TypeScript lives, which is what the convention scan reads. */
	source: z.string().default('src'),
	/** Where the game's compiled JavaScript lands, matching its tsconfig `outDir`. */
	compiled: z.string().default('dist'),
	/** Where to assemble the browser-side bundles. */
	out: z.string().default('build'),
	/** Targets `pack` builds when none are named on the command line. */
	targets: z.array(z.string()).default([]),
});

export const GamePackage = z.object({
	name: z.string(),
	version: z.string().default('0.0.0'),
	description: z.string().optional(),
	/** Display name for the installed app, defaulting to the unscoped package name. */
	productName: z.string().optional(),
	sumeria: BuildOptions.prefault({}),
});

export interface GamePackage extends z.infer<typeof GamePackage> {}

interface Game extends z.infer<typeof BuildOptions> {
	/** The package name with any leading scope stripped. */
	id: string;
	name: string;
	version: string;
	description?: string;
}

function gameOf(pkg: GamePackage): Game {
	const id = pkg.name.replace(/^@[^/]+\//, '');

	return { ...pkg.sumeria, id, name: pkg.productName ?? id, version: pkg.version, description: pkg.description };
}

/**
 * Generated sources live in the source tree so the game's own tsconfig compiles them.
 * The name is not dot-prefixed because TypeScript's wildcard includes skip dot-directories.
 */
const generatedDir = 'generated';

interface Found {
	/** The file's base name, which is both the export name and the type name. */
	name: string;
	path: string;
}

function scan(dir: string, ext: string): Found[] {
	if (!fs.existsSync(dir)) return [];

	const found: Found[] = [];

	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		if (!entry.isFile() || extname(entry.name) !== ext) continue;

		found.push({ name: basename(entry.name, ext), path: join(dir, entry.name) });
	}

	return found.sort((a, b) => a.name.localeCompare(b.name));
}

/** A relative ESM specifier from `from` to `to`, with TypeScript's `.js` extension. */
function specifier(from: string, to: string): string {
	const path = relative(from, to.replace(/\.ts$/, '.js')).split(sep).join(posix.sep);

	return path.startsWith('.') ? path : './' + path;
}

const header = '// Generated by @sumeria/app. Do not edit; your changes will be overwritten.\n';

interface Generated {
	dir: string;
	entities: Found[];
	renders: Found[];
	shaders: Found[];
	controls: Controls | null;
	/** Relative specifier from the compiled generated directory to the page. */
	page: string;
}

function generate({ dir, entities, renders, shaders, controls, page }: Generated): void {
	fs.rmSync(dir, { recursive: true, force: true });
	fs.mkdirSync(dir, { recursive: true });

	const shaderEntries = shaders.map(
		s => `shaders.set(${JSON.stringify(s.name)}, ${JSON.stringify(fs.readFileSync(s.path, 'utf8'))});`
	);

	const files: Record<string, string[]> = {
		'entities.ts': [
			header,
			"import { register } from '@sumeria/core';",
			...entities.map(e => `import { ${e.name} } from '${specifier(dir, e.path)}';`),
			'',
			`register(${entities.map(e => e.name).join(', ')});`,
			'',
		],

		'renders.ts': [
			header,
			"import { renderers, shaders } from '@sumeria/render';",
			...renders.map(r => `import { ${r.name} } from '${specifier(dir, r.path)}';`),
			'',
			...renders.map(r => `renderers.set(${JSON.stringify(r.name)}, ${r.name});`),
			...shaderEntries,
			'',
		],

		'controls.ts': [
			header,
			"import type { Controls } from '@sumeria/core';",
			'',
			`const controls: Controls = ${JSON.stringify(controls ?? {}, null, '\t')};`,
			'',
			'export default controls;',
			'',
		],

		'client.ts': [
			header,
			"import { input } from '@sumeria/client';",
			"import '@sumeria/client/main';",
			"import controls from './controls.js';",
			'',
			'input.bind(controls);',
			'',
		],

		'render.ts': [header, "import './renders.js';", "import '@sumeria/render/main';", ''],

		'server.ts': [header, "import './entities.js';", "import '@sumeria/app/server_thread';", ''],

		'electron.ts': [
			header,
			"import { config } from '@sumeria/app/config';",
			"import '@sumeria/app';",
			'',
			"config.server = new URL('server.js', import.meta.url);",
			`config.page = new URL(${JSON.stringify(page)}, import.meta.url);`,
			'',
		],
	};

	for (const [name, lines] of Object.entries(files)) {
		fs.writeFileSync(join(dir, name), lines.join('\n'));
	}
}

interface Bundle {
	out: string;
	entry: string;
}

async function bundle(target: Bundle, out: string, dev: boolean): Promise<io.jobs.JobResult> {
	try {
		const result = await esbuild.build({
			entryPoints: [target.entry],
			outfile: join(out, target.out),
			bundle: true,
			format: 'esm',
			platform: 'browser',
			target: 'chrome120',
			// Identifiers are left alone so `constructor.name` stays meaningful.
			minifyWhitespace: !dev,
			minifySyntax: !dev,
			minifyIdentifiers: false,
			keepNames: true,
			// Linked rather than inline: an inline map adds hundreds of megabytes to a
			// file the browser parses on every load.
			sourcemap: dev ? 'linked' : false,
			logLevel: 'silent',
		});

		const warnings = result.warnings.length ? ` (${result.warnings.length} warnings)` : '';
		return { status: 'succeeded', text: target.out + warnings };
	} catch (error) {
		return { status: 'failed', text: `${target.out}: ${io.errorText(error)}` };
	}
}

type Platform = 'linux' | 'win' | 'mac';

const platforms = ['linux', 'win', 'mac'] as const satisfies Platform[];

const hostPlatform: Platform = process.platform === 'win32' ? 'win' : process.platform === 'darwin' ? 'mac' : 'linux';

/** electron-builder target names that belong to exactly one platform. */
const platformOf: Record<string, Platform> = {
	appimage: 'linux',
	deb: 'linux',
	rpm: 'linux',
	snap: 'linux',
	pacman: 'linux',
	apk: 'linux',
	freebsd: 'linux',
	p5p: 'linux',
	nsis: 'win',
	'nsis-web': 'win',
	portable: 'win',
	appx: 'win',
	msi: 'win',
	'msi-wrapped': 'win',
	squirrel: 'win',
	dmg: 'mac',
	pkg: 'mac',
	mas: 'mac',
	'mas-dev': 'mac',
};

const spelling: Record<string, string> = { appimage: 'AppImage', 'nsis-web': 'nsis-web' };

const platformDefault: Record<Platform, string> = { linux: 'AppImage', win: 'nsis', mac: 'dmg' };

function isPlatform(value: string): value is Platform {
	return platforms.includes(value as Platform);
}

/**
 * Group target names by the platform that builds them.
 * A bare platform name means that platform's default, and `<platform>:<target>` names
 * anything the table does not cover.
 */
function targetsFor(names: string[]): Record<Platform, string[]> {
	const grouped: Record<Platform, string[]> = { linux: [], win: [], mac: [] };

	if (!names.length) grouped[hostPlatform].push(platformDefault[hostPlatform]);

	for (const name of names) {
		const [head, tail] = name.includes(':') ? name.split(':', 2) : [name, undefined];
		const key = head.toLowerCase();

		if (tail !== undefined) {
			if (!isPlatform(key)) io.exit(`Unknown platform "${head}" in target "${name}"`, 1);
			grouped[key].push(tail);
			continue;
		}

		if (isPlatform(key)) {
			grouped[key].push(platformDefault[key]);
			continue;
		}

		const platform = platformOf[key];

		if (!platform)
			io.exit(
				`Unknown target "${name}". Use one of ${Object.keys(platformOf).join(', ')},`
					+ ' a platform name, or <platform>:<target>.',
				1
			);

		grouped[platform].push(spelling[key] ?? key);
	}

	return grouped;
}

/**
 * Kept out of the packaged `node_modules`: supplied by the Electron runtime, only used
 * while building, or already inlined into the browser bundles.
 */
const notPackaged = [
	'electron',
	'electron-builder',
	'esbuild',
	'zod',
	'@babylonjs/core',
	'@sumeria/client',
	'@sumeria/render',
];

/**
 * The packaged app is the project itself: Electron's main process and the integrated
 * server are plain Node modules, so electron-builder packs them and their dependencies
 * rather than us bundling them.
 */
function builderConfig(game: Game, main: string, icon: string | null, targets: Record<Platform, string[]>) {
	const { version } = JSON.parse(fs.readFileSync(join(packageDir('electron'), 'package.json'), 'utf8')) as {
		version: string;
	};

	return {
		appId: game.appId ?? `com.${game.id.replaceAll('-', '')}.app`,
		productName: game.name,
		// The game depends on Electron through `@sumeria/app`, so it is not in its own tree.
		electronVersion: version,
		directories: { output: 'release' },
		artifactName: '${name}-${version}.${ext}',
		extraMetadata: {
			name: game.id,
			productName: game.name,
			version: game.version,
			description: game.description,
			type: 'module',
			main,
		},
		files: [`${game.compiled}/**/*`, `${game.out}/**/*`, 'package.json', '!**/*.map'],
		ignoredProductionDependencies: notPackaged,
		...(icon ? { icon } : {}),
		linux: { target: targets.linux, category: 'Game' },
		win: { target: targets.win },
		mac: { target: targets.mac, category: 'public.app-category.games' },
	};
}

async function run(command: string, args: string[], env: NodeJS.ProcessEnv = process.env): Promise<number> {
	return await new Promise((resolve, reject) => {
		const child = spawn(command, args, { stdio: 'inherit', env });

		child.on('error', reject);
		child.on('exit', code => resolve(code ?? 0));
	});
}

/**
 * The directory of one of this package's own dependencies.
 * Games reach the toolchain through `@sumeria/app`, so it is not in their own tree.
 */
function packageDir(name: string): string {
	const require = createRequire(import.meta.url);

	let dir: string;

	try {
		dir = dirname(require.resolve(name));
	} catch (error) {
		io.exit(`Could not find ${name}: ${io.errorText(error)}`, 1);
	}

	while (!fs.existsSync(join(dir, 'package.json'))) {
		const parent = dirname(dir);

		if (parent === dir) io.exit(`Could not find the package directory for ${name}`, 1);

		dir = parent;
	}

	return dir;
}

/** Runs the app in Electron, resolving with its exit code. */
async function launch(entry: string, args: string[]): Promise<number> {
	let electron: string;

	try {
		// The package's entry point is the path to the binary.
		electron = ((await import('electron')) as unknown as { default: string }).default;
	} catch (error) {
		io.exit(`Could not find Electron: ${io.errorText(error)}`, 1);
	}

	// Some toolchains export this to make the binary behave as plain Node,
	// which would start the app with none of the Electron APIs available.
	const env = { ...process.env };
	delete env.ELECTRON_RUN_AS_NODE;

	return await run(electron, [entry, ...args], env);
}

export async function main(argv: string[]): Promise<void> {
	const { values, positionals } = parseArgs({
		args: argv,
		allowPositionals: true,
		options: {
			project: { type: 'string', short: 'p', default: '.' },
			dev: { type: 'boolean', default: false },
			'skip-compile': { type: 'boolean', default: false },
			verbose: { type: 'boolean', short: 'v', default: false },
			help: { type: 'boolean', short: 'h', default: false },
		},
	});

	const command = positionals[0] ?? 'build';

	if (values.help || !['build', 'dev', 'pack'].includes(command)) {
		io.log('Usage: sumeria build [options]');
		io.log('       sumeria dev [options] [-- <electron args>]');
		io.log('       sumeria pack [options] [targets...]\n');
		io.log('  build              assemble the app');
		io.log('  dev                assemble unminified, then run it in Electron');
		io.log('  pack               assemble, then package with electron-builder\n');
		io.log('  -p, --project      path to the game package (default: .)');
		io.log('      --dev          emit sourcemaps and skip minification');
		io.log('      --skip-compile reuse the existing compiled output instead of running tsc');
		io.log('  -v, --verbose      show debug output\n');
		io.log('Targets are electron-builder target names, a platform name for its default,');
		io.log("or <platform>:<target>. Without any, the host platform's default is built.");
		return;
	}

	const dev = values.dev || command === 'dev';

	io._setDebugOutput(values.verbose);

	const root = resolve(values.project);
	const packagePath = join(root, 'package.json');

	if (!fs.existsSync(packagePath)) io.exit(`No package.json at ${packagePath}`, 1);

	const game = gameOf(io.readJSON(packagePath, GamePackage));

	io.info(`Building ${game.name} (${game.id}) v${game.version}`);

	const source = resolve(root, game.source);

	if (!fs.existsSync(source)) io.exit(`No source directory at ${source}`, 1);

	const entities = io.track('Scanning entities', () => scan(join(source, 'entities'), '.ts'));
	const renders = io.track('Scanning renderers', () => scan(join(source, 'render'), '.ts'));
	const shaders = io.track('Scanning shaders', () => scan(join(source, 'shaders'), '.glslx'));

	io.debug(`Found ${entities.length} entities, ${renders.length} renderers, ${shaders.length} shaders`);

	if (!entities.length) io.warn(`No entities found in ${join(source, 'entities')}`);

	for (const entity of entities) {
		if (!renders.some(render => render.name === entity.name))
			io.warnOnce(`No renderer in ${join(game.source, 'render')} for "${entity.name}"; it will be invisible`);
	}

	// Validated on the way in, so a bad binding is a build error rather than a key
	// that silently never fires.
	const controlsPath = resolve(root, game.controls);
	const controls = fs.existsSync(controlsPath)
		? io.track('Reading controls', () => io.readJSON(controlsPath, ControlsSchema))
		: null;

	if (controls) io.debug(`Bound ${Object.keys(controls).length} actions`);

	const out = resolve(root, game.out);
	const compiled = resolve(root, game.compiled);

	io.track('Generating entry points', () =>
		generate({
			dir: join(source, generatedDir),
			entities,
			renders,
			shaders,
			controls,
			page: specifier(join(compiled, generatedDir), join(out, 'index.html')),
		})
	);

	if (!values['skip-compile']) io.trackCommand('Compiling', 'npx', 'tsc', '--project', root);

	if (!fs.existsSync(join(compiled, generatedDir)))
		io.exit(`Nothing compiled at ${join(compiled, generatedDir)}. Check "compiled" in ${packagePath}.`, 1);

	fs.rmSync(out, { recursive: true, force: true });
	fs.mkdirSync(out, { recursive: true });

	const bundles: Bundle[] = [
		{ out: 'main.js', entry: join(compiled, generatedDir, 'client.js') },
		{ out: 'render.js', entry: join(compiled, generatedDir, 'render.js') },
	];

	const results = await io.jobs.runWithData(
		{
			concurrency: bundles.length,
			jobStartText: 'Bundling',
			run: target => bundle(target, out, dev),
			name: target => target.out,
		},
		bundles
	);

	if (results.failed) io.exit(`${results.failed} of ${bundles.length} bundles failed`, 1);

	io.track('Copying the page', () =>
		fs.copyFileSync(fileURLToPath(import.meta.resolve('@sumeria/client/index.html')), join(out, 'index.html'))
	);

	let icon: string | null = null;

	if (game.icon) {
		const from = resolve(root, game.icon);

		if (!fs.existsSync(from)) io.exit(`Icon not found: ${from}`, 1);

		const to = join(out, 'icon' + extname(from));
		io.track('Copying the icon', () => fs.copyFileSync(from, to));
		icon = relative(root, to).split(sep).join(posix.sep);
	} else if (command !== 'dev') {
		io.warnOnce('No "sumeria.icon" in package.json; electron-builder will use its default.');
	}

	const entry = join(compiled, generatedDir, 'electron.js');

	io.info(`Assembled ${relative(root, out) || '.'}`);

	if (command === 'dev') {
		io.info(`Starting ${game.name}`);

		// Anything after `--` belongs to Electron, not to us.
		const code = await launch(entry, positionals.slice(1));

		if (code) io.exit(`${game.name} exited with code ${code}`, code);
		return;
	}

	const named = command === 'pack' ? positionals.slice(1) : [];
	const targets = targetsFor(named.length ? named : game.targets);

	io.debug('Targets: ' + platforms.map(p => `${p}=[${targets[p].join(', ')}]`).join(' '));

	// Only packaging reads this, but `build` writes it too so `pack` can run on its own.
	const builderPath = join(root, 'electron-builder.json');
	const main = relative(root, entry).split(sep).join(posix.sep);

	io.track('Writing the electron-builder config', () =>
		fs.writeFileSync(builderPath, JSON.stringify(builderConfig(game, main, icon, targets), null, '\t') + '\n')
	);

	if (command !== 'pack') return;

	io.info('Packaging');

	const args = [join(packageDir('electron-builder'), 'cli.js'), '--config', builderPath, '--projectDir', root];

	for (const platform of platforms) {
		if (targets[platform].length) args.push(`--${platform}`);
	}

	const code = await run(process.execPath, args);

	if (code) io.exit(`electron-builder exited with code ${code}`, code);
}

await main(process.argv.slice(2));
