#!/usr/bin/env node
import { ControlsConfig } from '@sumeria/client/controls';
import * as esbuild from 'esbuild';
import * as io from 'ioium/node';
import * as fs from 'node:fs';
import { basename, dirname, extname, join, posix, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import * as z from 'zod';

/**
 * A game's build configuration.
 *
 * Everything the app shell needs that can not be inferred from the source
 * tree: identity, versioning, and the icon.
 */
export const GameConfig = z.object({
	/** Namespace for this game's content. Entity type ids are `<id>:<name>`. */
	id: z.string().regex(/^[a-z0-9][a-z0-9-]*$/, 'expected lowercase letters, digits and dashes'),
	/** Display name, used for the installed app. */
	name: z.string(),
	version: z.string().default('0.0.0'),
	description: z.string().optional(),
	/** Reverse-DNS id for the packaged app. Derived from `id` when omitted. */
	appId: z.string().optional(),
	/** Path to the app icon, relative to the config file. */
	icon: z.string().optional(),
	/**
	 * The unqualified entity name to spawn for each connected client, for
	 * example `duck`. Without it, clients connect as spectators.
	 */
	player: z.string().optional(),
	/** Path to the controls config, relative to the config file. Optional. */
	controls: z.string().default('controls.json'),
	/** Where the game's TypeScript lives. This is what the convention scan reads. */
	source: z.string().default('src'),
	/** Where the game's compiled JavaScript lands, matching its tsconfig `outDir`. */
	compiled: z.string().default('dist'),
	/** Where to assemble the app. */
	out: z.string().default('build'),
});

export interface GameConfig extends z.infer<typeof GameConfig> {}

/**
 * Generated sources go in the source tree rather than beside the config, so
 * the game's own tsconfig compiles them and its tests can import the manifest
 * with types. The name is deliberately not dot-prefixed: TypeScript's wildcard
 * includes skip dot-directories.
 */
const generatedDir = 'generated';

/** A file picked up by the convention scan. */
interface Found {
	/** Unqualified content name, for example `duck`. */
	name: string;
	/** Absolute path to the file. */
	path: string;
	/** The export the content is expected under, for example `Duck`. */
	export: string;
}

/**
 * Collect the contents of one convention directory.
 *
 * The unqualified name is the file's base name lowercased, so
 * `entities/Duck.ts` becomes `duck` and its type id becomes `<game>:duck`.
 */
function scan(dir: string, ext: string): Found[] {
	if (!fs.existsSync(dir)) return [];

	const found = new Map<string, Found>();

	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		if (!entry.isFile() || extname(entry.name) !== ext) continue;

		const stem = basename(entry.name, ext);
		const name = stem.toLowerCase();
		const existing = found.get(name);

		if (existing)
			throw new Error(
				`${join(dir, entry.name)} and ${existing.path} both map to "${name}".`
					+ ' Content names are case-insensitive, so rename one of them.'
			);

		found.set(name, { name, path: join(dir, entry.name), export: stem });
	}

	return [...found.values()].sort((a, b) => a.name.localeCompare(b.name));
}

/** Turn an absolute path into a relative ESM specifier from `from`, as TypeScript wants it. */
function specifier(from: string, to: string): string {
	const path = relative(from, to.replace(/\.ts$/, '.js')).split(sep).join(posix.sep);

	return path.startsWith('.') ? path : './' + path;
}

const header = '// Generated by @sumeria/app. Do not edit; your changes will be overwritten.\n';

/**
 * Write the manifest and entry points that wire the game into the engine.
 *
 * This is the point of the convention scan: the game never imports the
 * engine's lifecycle, the generated code does it.
 */
function generate(
	dir: string,
	config: GameConfig,
	entities: Found[],
	shaders: Found[],
	controls: ControlsConfig | null
): void {
	fs.rmSync(dir, { recursive: true, force: true });
	fs.mkdirSync(dir, { recursive: true });

	// Entity classes must be exported under their file's base name.
	const imports = entities.map(e => `import { ${e.export} } from '${specifier(dir, e.path)}';`);

	const entries = entities.map(e => `\n\t\t${JSON.stringify(e.name)}: ${e.export},`).join('');

	const fields = [`\tid: ${JSON.stringify(config.id)},`, `\tentities: {${entries}\n\t},`];

	if (shaders.length) {
		const sources = shaders
			.map(s => `\n\t\t${JSON.stringify(s.name)}: ${JSON.stringify(fs.readFileSync(s.path, 'utf8'))},`)
			.join('');

		fields.push(`\tshaders: {${sources}\n\t},`);
	}

	if (config.player) fields.push(`\tplayer: ${JSON.stringify(config.player)},`);

	if (controls) fields.push(`\tcontrols: ${JSON.stringify(controls, null, '\t').replaceAll('\n', '\n\t')},`);

	const files: Record<string, string[]> = {
		'manifest.ts': [
			header,
			"import { defineGame } from '@sumeria/core';",
			...imports,
			'',
			'export default defineGame({',
			...fields,
			'});',
			'',
		],

		'main.ts': [
			header,
			"import { start } from '@sumeria/client';",
			"import game from './manifest.js';",
			'',
			'start(game);',
			'',
		],

		'server.ts': [
			header,
			"import { start } from '@sumeria/app/server_thread';",
			"import game from './manifest.js';",
			'',
			'start(game);',
			'',
		],
	};

	for (const [name, lines] of Object.entries(files)) {
		fs.writeFileSync(join(dir, name), lines.join('\n'));
	}
}

/** One esbuild output. */
interface Bundle {
	out: string;
	entry: string;
	node?: boolean;
}

/**
 * Electron supplies its own runtime, and the other two are optional native
 * speedups for ws that are frequently not installed at all.
 */
const neverBundle = ['electron', 'bufferutil', 'utf-8-validate'];

/** Lets the CommonJS dependencies we inline keep calling `require`. */
const requireShim =
	"import { createRequire as __sumeriaRequire } from 'node:module';\n"
	+ 'const require = __sumeriaRequire(import.meta.url);\n';

async function bundle(target: Bundle, out: string, dev: boolean): Promise<io.jobs.JobResult> {
	try {
		const result = await esbuild.build({
			entryPoints: [target.entry],
			outfile: join(out, target.out),
			bundle: true,
			format: 'esm',
			platform: target.node ? 'node' : 'browser',
			target: target.node ? 'node22' : 'chrome120',
			// Everything is inlined, so the packaged app carries no node_modules.
			external: target.node ? neverBundle : [],
			banner: target.node ? { js: requireShim } : undefined,
			sourcemap: dev ? 'inline' : false,
			minify: !dev,
			logLevel: 'silent',
		});

		const warnings = result.warnings.length ? ` (${result.warnings.length} warnings)` : '';
		return { status: 'succeeded', text: target.out + warnings };
	} catch (error) {
		return { status: 'failed', text: `${target.out}: ${io.errorText(error)}` };
	}
}

/** electron-builder's config, written next to the game config. */
function builderConfig(config: GameConfig, app: string, icon: string | null) {
	return {
		appId: config.appId ?? `com.${config.id.replaceAll('-', '')}.app`,
		productName: config.name,
		directories: { app, output: 'release' },
		files: ['**/*'],
		...(icon ? { icon } : {}),
		linux: { target: ['AppImage'], category: 'Game' },
		win: { target: ['nsis'] },
		mac: { target: ['dmg'], category: 'public.app-category.games' },
	};
}

export async function main(argv: string[]): Promise<void> {
	const { values, positionals } = parseArgs({
		args: argv,
		allowPositionals: true,
		options: {
			config: { type: 'string', short: 'c', default: 'game.json' },
			dev: { type: 'boolean', default: false },
			'skip-compile': { type: 'boolean', default: false },
			verbose: { type: 'boolean', short: 'v', default: false },
			help: { type: 'boolean', short: 'h', default: false },
		},
	});

	const command = positionals[0] ?? 'build';

	if (values.help || !['build', 'pack'].includes(command)) {
		io.log('Usage: sumeria [build|pack] [options]\n');
		io.log('  build              assemble the app into the output directory');
		io.log('  pack               assemble, then package with electron-builder\n');
		io.log('  -c, --config       path to the game config (default: game.json)');
		io.log('      --dev          keep sourcemaps and skip minification');
		io.log('      --skip-compile reuse the existing compiled output instead of running tsc');
		io.log('  -v, --verbose      show debug output');
		return;
	}

	io._setDebugOutput(values.verbose);

	const configPath = resolve(values.config);

	if (!fs.existsSync(configPath)) io.exit(`No game config at ${configPath}`, 1);

	const root = dirname(configPath);
	const config = io.readJSON(configPath, GameConfig);

	io.info(`Building ${config.name} (${config.id}) v${config.version}`);

	const source = resolve(root, config.source);

	if (!fs.existsSync(source)) io.exit(`No source directory at ${source}`, 1);

	const entities = io.track('Scanning entities', () => scan(join(source, 'entities'), '.ts'));
	const shaders = io.track('Scanning shaders', () => scan(join(source, 'shaders'), '.glslx'));

	io.debug(`Found ${entities.length} entities, ${shaders.length} shaders`);

	if (!entities.length) io.warn(`No entities found in ${join(source, 'entities')}`);

	// Validated here with the client's own schema, so a bad binding is a build
	// error rather than a key that silently never fires.
	const controlsPath = resolve(root, config.controls);
	const controls = fs.existsSync(controlsPath)
		? io.track('Reading controls', () => io.readJSON(controlsPath, ControlsConfig))
		: null;

	if (controls) io.debug(`Bound ${Object.keys(controls).length} actions`);

	io.track('Generating entry points', () =>
		generate(join(source, generatedDir), config, entities, shaders, controls)
	);

	// Compiles the generated sources along with the game's own.
	if (!values['skip-compile']) io.trackCommand('Compiling', 'npx', 'tsc', '--project', root);

	const compiled = resolve(root, config.compiled);

	if (!fs.existsSync(join(compiled, generatedDir)))
		io.exit(`Nothing compiled at ${join(compiled, generatedDir)}. Check "compiled" in ${values.config}.`, 1);

	const out = resolve(root, config.out);
	fs.rmSync(out, { recursive: true, force: true });
	fs.mkdirSync(out, { recursive: true });

	const targets: Bundle[] = [
		{ out: 'electron.js', entry: fileURLToPath(import.meta.resolve('@sumeria/app')), node: true },
		{ out: 'server.js', entry: join(compiled, generatedDir, 'server.js'), node: true },
		{ out: 'main.js', entry: join(compiled, generatedDir, 'main.js') },
		{ out: 'render.js', entry: fileURLToPath(import.meta.resolve('@sumeria/render/main')) },
	];

	const results = await io.jobs.runWithData(
		{
			concurrency: targets.length,
			jobStartText: 'Bundling',
			run: target => bundle(target, out, values.dev),
			name: target => target.out,
		},
		targets
	);

	if (results.failed) io.exit(`${results.failed} of ${targets.length} bundles failed`, 1);

	io.track('Copying the page', () =>
		fs.copyFileSync(fileURLToPath(import.meta.resolve('@sumeria/client/index.html')), join(out, 'index.html'))
	);

	let icon: string | null = null;

	if (config.icon) {
		const from = resolve(root, config.icon);

		if (!fs.existsSync(from)) io.exit(`Icon not found: ${from}`, 1);

		const to = join(out, 'icon' + extname(from));
		io.track('Copying the icon', () => fs.copyFileSync(from, to));
		icon = relative(root, to);
	} else {
		io.warnOnce('No "icon" in the game config; electron-builder will use its default.');
	}

	// electron-builder needs a package.json describing the app it packages.
	io.track('Writing the app manifest', () =>
		fs.writeFileSync(
			join(out, 'package.json'),
			JSON.stringify(
				{
					name: config.id,
					productName: config.name,
					version: config.version,
					description: config.description,
					main: 'electron.js',
					type: 'module',
				},
				null,
				'\t'
			) + '\n'
		)
	);

	const builderPath = join(root, 'electron-builder.json');

	io.track('Writing the electron-builder config', () =>
		fs.writeFileSync(
			builderPath,
			JSON.stringify(builderConfig(config, relative(root, out), icon), null, '\t') + '\n'
		)
	);

	io.info(`Assembled ${relative(root, out) || '.'}`);

	if (command !== 'pack') return;

	io.trackCommand('Packaging', 'npx', 'electron-builder', '--config', relative(root, builderPath));
}

await main(process.argv.slice(2));
