#!/usr/bin/env node
import { ControlsConfig } from '@sumeria/client/controls';
import type { Controls } from '@sumeria/core';
import * as esbuild from 'esbuild';
import * as io from 'ioium/node';
import { spawn } from 'node:child_process';
import * as fs from 'node:fs';
import { createRequire } from 'node:module';
import { basename, dirname, extname, join, posix, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import * as z from 'zod';

export const GameConfig = z.object({
	id: z.string().regex(/^[a-z0-9][a-z0-9-]*$/, 'expected lowercase letters, digits and dashes'),
	name: z.string(),
	version: z.string().default('0.0.0'),
	description: z.string().optional(),
	/** Reverse-DNS id for the packaged app, derived from `id` when omitted. */
	appId: z.string().optional(),
	/** Path to the app icon, relative to the config file. */
	icon: z.string().optional(),
	/** Name of the entity to spawn for each client; without it, clients are spectators. */
	player: z.string().optional(),
	/** Path to the controls config, relative to the config file. */
	controls: z.string().default('controls.json'),
	/** Where the game's TypeScript lives, which is what the convention scan reads. */
	source: z.string().default('src'),
	/** Where the game's compiled JavaScript lands, matching its tsconfig `outDir`. */
	compiled: z.string().default('dist'),
	/** Where to assemble the browser-side bundles. */
	out: z.string().default('build'),
});

export interface GameConfig extends z.infer<typeof GameConfig> {}

/**
 * Generated sources live in the source tree so the game's own tsconfig compiles them.
 * The name is not dot-prefixed because TypeScript's wildcard includes skip dot-directories.
 */
const generatedDir = 'generated';

interface Found {
	/** The file's base name, which is both the export name and the type name. */
	name: string;
	path: string;
}

function scan(dir: string, ext: string): Found[] {
	if (!fs.existsSync(dir)) return [];

	const found: Found[] = [];

	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		if (!entry.isFile() || extname(entry.name) !== ext) continue;

		found.push({ name: basename(entry.name, ext), path: join(dir, entry.name) });
	}

	return found.sort((a, b) => a.name.localeCompare(b.name));
}

/** A relative ESM specifier from `from` to `to`, with TypeScript's `.js` extension. */
function specifier(from: string, to: string): string {
	const path = relative(from, to.replace(/\.ts$/, '.js')).split(sep).join(posix.sep);

	return path.startsWith('.') ? path : './' + path;
}

const header = '// Generated by @sumeria/app. Do not edit; your changes will be overwritten.\n';

interface Generated {
	config: GameConfig;
	dir: string;
	entities: Found[];
	renders: Found[];
	shaders: Found[];
	controls: Controls | null;
	/** Relative specifier from the compiled generated directory to the page. */
	page: string;
}

function generate({ config, dir, entities, renders, shaders, controls, page }: Generated): void {
	fs.rmSync(dir, { recursive: true, force: true });
	fs.mkdirSync(dir, { recursive: true });

	const entityImports = entities.map(e => `import { ${e.name} } from '${specifier(dir, e.path)}';`);

	const fields = [
		`\tid: ${JSON.stringify(config.id)},`,
		`\tentities: [${entities.map(e => e.name).join(', ')}],`,
		'\tcontrols,',
	];

	if (config.player) fields.push(`\tplayer: ${JSON.stringify(config.player)},`);

	const renderImports = renders.map(r => `import { ${r.name} } from '${specifier(dir, r.path)}';`);

	const renderFields = [
		`\tid: ${JSON.stringify(config.id)},`,
		`\tentities: { ${renders.map(r => r.name).join(', ')} },`,
	];

	if (shaders.length) {
		const sources = shaders
			.map(s => `\n\t\t${JSON.stringify(s.name)}: ${JSON.stringify(fs.readFileSync(s.path, 'utf8'))},`)
			.join('');

		renderFields.push(`\tshaders: {${sources}\n\t},`);
	}

	const files: Record<string, string[]> = {
		'controls.ts': [
			header,
			"import type { Controls } from '@sumeria/core';",
			'',
			`const controls: Controls = ${JSON.stringify(controls ?? {}, null, '\t')};`,
			'',
			'export default controls;',
			'',
		],

		'manifest.ts': [
			header,
			"import { defineGame } from '@sumeria/core';",
			"import controls from './controls.js';",
			...entityImports,
			'',
			'export default defineGame({',
			...fields,
			'});',
			'',
		],

		'renders.ts': [
			header,
			"import type { RenderManifest } from '@sumeria/render';",
			...renderImports,
			'',
			'export default {',
			...renderFields,
			'} satisfies RenderManifest;',
			'',
		],

		'client.ts': [
			header,
			"import { start } from '@sumeria/client';",
			"import controls from './controls.js';",
			'',
			'start(controls);',
			'',
		],

		'render.ts': [
			header,
			"import { start } from '@sumeria/render';",
			"import renders from './renders.js';",
			'',
			'start(renders);',
			'',
		],

		'server.ts': [
			header,
			"import { start } from '@sumeria/app/server_thread';",
			"import game from './manifest.js';",
			'',
			'start(game);',
			'',
		],

		'electron.ts': [
			header,
			"import { start } from '@sumeria/app';",
			'',
			'start({',
			"\tserver: new URL('server.js', import.meta.url),",
			`\tpage: new URL(${JSON.stringify(page)}, import.meta.url),`,
			'});',
			'',
		],
	};

	for (const [name, lines] of Object.entries(files)) {
		fs.writeFileSync(join(dir, name), lines.join('\n'));
	}
}

interface Bundle {
	out: string;
	entry: string;
}

async function bundle(target: Bundle, out: string, dev: boolean): Promise<io.jobs.JobResult> {
	try {
		const result = await esbuild.build({
			entryPoints: [target.entry],
			outfile: join(out, target.out),
			bundle: true,
			format: 'esm',
			platform: 'browser',
			target: 'chrome120',
			// Identifiers are left alone so `constructor.name` stays meaningful.
			minifyWhitespace: !dev,
			minifySyntax: !dev,
			minifyIdentifiers: false,
			keepNames: true,
			// Linked rather than inline: an inline map adds hundreds of megabytes to a
			// file the browser parses on every load.
			sourcemap: dev ? 'linked' : false,
			logLevel: 'silent',
		});

		const warnings = result.warnings.length ? ` (${result.warnings.length} warnings)` : '';
		return { status: 'succeeded', text: target.out + warnings };
	} catch (error) {
		return { status: 'failed', text: `${target.out}: ${io.errorText(error)}` };
	}
}

/**
 * Kept out of the packaged `node_modules`: supplied by the Electron runtime, only used
 * while building, or already inlined into the browser bundles.
 */
const notPackaged = [
	'electron',
	'electron-builder',
	'esbuild',
	'zod',
	'@babylonjs/core',
	'@sumeria/client',
	'@sumeria/render',
];

/**
 * The packaged app is the project itself: Electron's main process and the integrated
 * server are plain Node modules, so electron-builder packs them and their dependencies
 * rather than us bundling them.
 */
function builderConfig(config: GameConfig, main: string, icon: string | null) {
	const { version } = JSON.parse(fs.readFileSync(join(packageDir('electron'), 'package.json'), 'utf8')) as {
		version: string;
	};

	return {
		appId: config.appId ?? `com.${config.id.replaceAll('-', '')}.app`,
		productName: config.name,
		// The game depends on Electron through `@sumeria/app`, so it is not in its own tree.
		electronVersion: version,
		directories: { output: 'release' },
		extraMetadata: {
			name: config.id,
			productName: config.name,
			version: config.version,
			description: config.description,
			type: 'module',
			main,
		},
		files: [`${config.compiled}/**/*`, `${config.out}/**/*`, 'package.json', '!**/*.map'],
		ignoredProductionDependencies: notPackaged,
		...(icon ? { icon } : {}),
		linux: { target: ['AppImage'], category: 'Game' },
		win: { target: ['nsis'] },
		mac: { target: ['dmg'], category: 'public.app-category.games' },
	};
}

async function run(command: string, args: string[], env: NodeJS.ProcessEnv = process.env): Promise<number> {
	return await new Promise((resolve, reject) => {
		const child = spawn(command, args, { stdio: 'inherit', env });

		child.on('error', reject);
		child.on('exit', code => resolve(code ?? 0));
	});
}

/**
 * The directory of one of this package's own dependencies.
 * Games reach the toolchain through `@sumeria/app`, so it is not in their own tree.
 */
function packageDir(name: string): string {
	const require = createRequire(import.meta.url);

	let dir: string;

	try {
		dir = dirname(require.resolve(name));
	} catch (error) {
		io.exit(`Could not find ${name}: ${io.errorText(error)}`, 1);
	}

	while (!fs.existsSync(join(dir, 'package.json'))) {
		const parent = dirname(dir);

		if (parent === dir) io.exit(`Could not find the package directory for ${name}`, 1);

		dir = parent;
	}

	return dir;
}

/** Runs the app in Electron, resolving with its exit code. */
async function launch(entry: string, args: string[]): Promise<number> {
	let electron: string;

	try {
		// The package's entry point is the path to the binary.
		electron = ((await import('electron')) as unknown as { default: string }).default;
	} catch (error) {
		io.exit(`Could not find Electron: ${io.errorText(error)}`, 1);
	}

	// Some toolchains export this to make the binary behave as plain Node,
	// which would start the app with none of the Electron APIs available.
	const env = { ...process.env };
	delete env.ELECTRON_RUN_AS_NODE;

	return await run(electron, [entry, ...args], env);
}

export async function main(argv: string[]): Promise<void> {
	const { values, positionals } = parseArgs({
		args: argv,
		allowPositionals: true,
		options: {
			config: { type: 'string', short: 'c', default: 'game.json' },
			dev: { type: 'boolean', default: false },
			'skip-compile': { type: 'boolean', default: false },
			verbose: { type: 'boolean', short: 'v', default: false },
			help: { type: 'boolean', short: 'h', default: false },
		},
	});

	const command = positionals[0] ?? 'build';

	if (values.help || !['build', 'dev', 'pack'].includes(command)) {
		io.log('Usage: sumeria [build|dev|pack] [options] [-- <electron args>]\n');
		io.log('  build              assemble the app');
		io.log('  dev                assemble unminified, then run it in Electron');
		io.log('  pack               assemble, then package with electron-builder\n');
		io.log('  -c, --config       path to the game config (default: game.json)');
		io.log('      --dev          emit sourcemaps and skip minification');
		io.log('      --skip-compile reuse the existing compiled output instead of running tsc');
		io.log('  -v, --verbose      show debug output');
		return;
	}

	const dev = values.dev || command === 'dev';

	io._setDebugOutput(values.verbose);

	const configPath = resolve(values.config);

	if (!fs.existsSync(configPath)) io.exit(`No game config at ${configPath}`, 1);

	const root = dirname(configPath);
	const config = io.readJSON(configPath, GameConfig);

	io.info(`Building ${config.name} (${config.id}) v${config.version}`);

	const source = resolve(root, config.source);

	if (!fs.existsSync(source)) io.exit(`No source directory at ${source}`, 1);

	const entities = io.track('Scanning entities', () => scan(join(source, 'entities'), '.ts'));
	const renders = io.track('Scanning renderers', () => scan(join(source, 'render'), '.ts'));
	const shaders = io.track('Scanning shaders', () => scan(join(source, 'shaders'), '.glslx'));

	io.debug(`Found ${entities.length} entities, ${renders.length} renderers, ${shaders.length} shaders`);

	if (!entities.length) io.warn(`No entities found in ${join(source, 'entities')}`);

	for (const entity of entities) {
		if (!renders.some(render => render.name === entity.name))
			io.warnOnce(`No renderer in ${join(config.source, 'render')} for "${entity.name}"; it will be invisible`);
	}

	if (config.player) {
		// Entity types are keyed by class name, so the config is matched against the file names.
		const player = entities.find(entity => entity.name.toLowerCase() === config.player!.toLowerCase());

		if (!player) io.exit(`No entity named "${config.player}" to spawn players from`, 1);

		config.player = player.name;
	}

	// Validated with the client's own schema, so a bad binding is a build error
	// rather than a key that silently never fires.
	const controlsPath = resolve(root, config.controls);
	const controls = fs.existsSync(controlsPath)
		? io.track('Reading controls', () => io.readJSON(controlsPath, ControlsConfig))
		: null;

	if (controls) io.debug(`Bound ${Object.keys(controls).length} actions`);

	const out = resolve(root, config.out);
	const compiled = resolve(root, config.compiled);

	io.track('Generating entry points', () =>
		generate({
			config,
			dir: join(source, generatedDir),
			entities,
			renders,
			shaders,
			controls,
			page: specifier(join(compiled, generatedDir), join(out, 'index.html')),
		})
	);

	if (!values['skip-compile']) io.trackCommand('Compiling', 'npx', 'tsc', '--project', root);

	if (!fs.existsSync(join(compiled, generatedDir)))
		io.exit(`Nothing compiled at ${join(compiled, generatedDir)}. Check "compiled" in ${values.config}.`, 1);

	fs.rmSync(out, { recursive: true, force: true });
	fs.mkdirSync(out, { recursive: true });

	const targets: Bundle[] = [
		{ out: 'main.js', entry: join(compiled, generatedDir, 'client.js') },
		{ out: 'render.js', entry: join(compiled, generatedDir, 'render.js') },
	];

	const results = await io.jobs.runWithData(
		{
			concurrency: targets.length,
			jobStartText: 'Bundling',
			run: target => bundle(target, out, dev),
			name: target => target.out,
		},
		targets
	);

	if (results.failed) io.exit(`${results.failed} of ${targets.length} bundles failed`, 1);

	io.track('Copying the page', () =>
		fs.copyFileSync(fileURLToPath(import.meta.resolve('@sumeria/client/index.html')), join(out, 'index.html'))
	);

	let icon: string | null = null;

	if (config.icon) {
		const from = resolve(root, config.icon);

		if (!fs.existsSync(from)) io.exit(`Icon not found: ${from}`, 1);

		const to = join(out, 'icon' + extname(from));
		io.track('Copying the icon', () => fs.copyFileSync(from, to));
		icon = relative(root, to).split(sep).join(posix.sep);
	} else if (command !== 'dev') {
		io.warnOnce('No "icon" in the game config; electron-builder will use its default.');
	}

	const entry = join(compiled, generatedDir, 'electron.js');

	io.info(`Assembled ${relative(root, out) || '.'}`);

	if (command === 'dev') {
		io.info(`Starting ${config.name}`);

		// Anything after `--` belongs to Electron, not to us.
		const code = await launch(entry, positionals.slice(1));

		if (code) io.exit(`${config.name} exited with code ${code}`, code);
		return;
	}

	// Only packaging reads this, but `build` writes it too so `pack` can run on its own.
	const builderPath = join(root, 'electron-builder.json');
	const main = relative(root, entry).split(sep).join(posix.sep);

	io.track('Writing the electron-builder config', () =>
		fs.writeFileSync(builderPath, JSON.stringify(builderConfig(config, main, icon), null, '\t') + '\n')
	);

	if (command !== 'pack') return;

	io.info('Packaging');

	const code = await run(process.execPath, [
		join(packageDir('electron-builder'), 'cli.js'),
		'--config',
		builderPath,
		'--projectDir',
		root,
	]);

	if (code) io.exit(`electron-builder exited with code ${code}`, code);
}

await main(process.argv.slice(2));
