import { app, BrowserWindow } from 'electron';
import * as io from 'ioium/node';
import { join } from 'node:path';
import { Worker } from 'node:worker_threads';
import type { FromServer } from './server_thread.js';

/**
 * The integrated server runs in a worker thread next to us.
 * `server.js` is generated by the build, so it carries the game's manifest.
 */
const serverPort = new Promise<number>((resolve, reject) => {
	const thread = new Worker(join(import.meta.dirname, 'server.js'));

	thread.on('message', (message: FromServer) => {
		if (message.$ === 'listen') resolve(message.port);
	});

	thread.on('error', reject);
	thread.on('exit', code => reject(new Error(`The server thread exited with code ${code}`)));
});

app.whenReady()
	.then(async () => {
		const port = await serverPort;
		io.debug('[server] listening on port', port);

		const window = new BrowserWindow();

		// The renderer needs to know where to connect; a query param avoids
		// standing up an IPC channel just to hand over a number.
		await window.loadFile(join(import.meta.dirname, 'index.html'), { query: { port: String(port) } });
	})
	.catch((error: unknown) => {
		io.error(error);
		app.exit(1);
	});

app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') app.quit();
});
