name: Release

on:
    release:
        types: [created]

jobs:
    ci:
        uses: ./.github/workflows/ci.yaml
        permissions:
            contents: read
    release:
        runs-on: ubuntu-latest
        needs: ci
        permissions:
            id-token: write
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: latest
                  registry-url: https://registry.npmjs.org/

            - name: Use latest npm version
              run: npm install -g npm@latest

            - name: Install dependencies
              run: npm ci

            - name: Resolve package
              id: resolve
              run: |
                  PACKAGE="$(echo ${{ github.event.release.tag_name }} | sed 's/@.*$//')"
                  if [ "$PACKAGE" = "sumeria" ]; then
                      PACKAGE="sdk"
                  fi
                  if [ ! -d "src/$PACKAGE" ]; then
                      echo "Package directory not found"
                      exit 1
                  fi
                  echo "path=src/$PACKAGE" >> $GITHUB_OUTPUT
                  echo "::debug::Resolved package to 'src/$PACKAGE'"

            - name: Build
              run: npx tsc -b

            - name: Publish
              run: npm publish --access=public --provenance
              working-directory: ${{ steps.resolve.outputs.path }}
